### PR TITLE
Initial client

### PR DESCRIPTION
**Pull request by michalpristas**
Matches the one from beats repo

running mage update will generate client code and injects a license header

cc @ph @blakerouse

### CODE REVIEW

**Comment by ph** [comment]
When we start creating the new contracts, let's add a changelog so we can communicate ou changes with endpoint.

**Comment by ruflin** [comment]
As I expect all of this code to be under ES license I don't think we need the x-pack prefix, it would only complicate the code structure. And yes, we need the headers.

**Comment by michalpristas** [comment]
updated with proto file license header generation
do we need some common license file here?

**Comment by ph** [comment]
lets get that merged @michalpristas to iterate.

**Pull request merged**
